[build-system]
requires = ["setuptools>=68,<77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ncv"
version = "0.1.0"
description = "A quick PyQt5 viewer for NetCDF files"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

dependencies = [
  "matplotlib",
  "netCDF4",
  "numpy",
  "PyQt5"
]

[[project.authors]]
name = "Sanjeev Bashyal"
email = "sanjeev.bashyal01@gmail.com"

[[project.authors]]
name = "Matthias Cuntz"

[project.optional-dependencies]
xarray = ["xarray"]
map = ["cartopy"]
test = ["pytest"]
full = ["xarray", "cartopy"]



[project.urls]
Homepage = "https://github.com/SanjeevBashyal/ncv"
Repository = "https://github.com/SanjeevBashyal/ncv"
"Bug Tracker" = "https://github.com/SanjeevBashyal/ncv/issues"

[project.scripts]
ncv = "ncv.__main__:main"

[tool.setuptools]
packages = ["ncv", "ncv.pyui"]

[tool.setuptools.package-data]
ncv = [
  "images/*.png",
  "images/*.ico",
  "ui/*.ui"
]
