# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ncv/ui/map_unavailable.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapUnavailablePanel(object):
    def setupUi(self, MapUnavailablePanel):
        MapUnavailablePanel.setObjectName("MapUnavailablePanel")
        MapUnavailablePanel.resize(640, 480)
        self.mainLayout = QtWidgets.QVBoxLayout(MapUnavailablePanel)
        self.mainLayout.setObjectName("mainLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.label_message = QtWidgets.QLabel(MapUnavailablePanel)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setWordWrap(True)
        self.label_message.setObjectName("label_message")
        self.mainLayout.addWidget(self.label_message)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem1)

        self.retranslateUi(MapUnavailablePanel)
        QtCore.QMetaObject.connectSlotsByName(MapUnavailablePanel)

    def retranslateUi(self, MapUnavailablePanel):
        _translate = QtCore.QCoreApplication.translate
        self.label_message.setText(_translate("MapUnavailablePanel", "Map view is unavailable."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MapUnavailablePanel = QtWidgets.QWidget()
    ui = Ui_MapUnavailablePanel()
    ui.setupUi(MapUnavailablePanel)
    MapUnavailablePanel.show()
    sys.exit(app.exec_())
