# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ncv/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NcvMainWindow(object):
    def setupUi(self, NcvMainWindow):
        NcvMainWindow.setObjectName("NcvMainWindow")
        NcvMainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(NcvMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralLayout.setContentsMargins(0, 0, 0, 0)
        self.centralLayout.setObjectName("centralLayout")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab_scatterPlot = QtWidgets.QWidget()
        self.tab_scatterPlot.setObjectName("tab_scatterPlot")
        self.tabWidget_main.addTab(self.tab_scatterPlot, "")
        self.tab_contourPlot = QtWidgets.QWidget()
        self.tab_contourPlot.setObjectName("tab_contourPlot")
        self.tabWidget_main.addTab(self.tab_contourPlot, "")
        self.tab_mapPlot = QtWidgets.QWidget()
        self.tab_mapPlot.setObjectName("tab_mapPlot")
        self.tabWidget_main.addTab(self.tab_mapPlot, "")
        self.tab_matrixDisplay = QtWidgets.QWidget()
        self.tab_matrixDisplay.setObjectName("tab_matrixDisplay")
        self.tabWidget_main.addTab(self.tab_matrixDisplay, "")
        self.centralLayout.addWidget(self.tabWidget_main)
        NcvMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(NcvMainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NcvMainWindow)

    def retranslateUi(self, NcvMainWindow):
        _translate = QtCore.QCoreApplication.translate
        NcvMainWindow.setWindowTitle(_translate("NcvMainWindow", "ncv"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_scatterPlot), _translate("NcvMainWindow", "Scatter/Line"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_contourPlot), _translate("NcvMainWindow", "Contour"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_mapPlot), _translate("NcvMainWindow", "Map"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_matrixDisplay), _translate("NcvMainWindow", "Matrix"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NcvMainWindow = QtWidgets.QMainWindow()
    ui = Ui_NcvMainWindow()
    ui.setupUi(NcvMainWindow)
    NcvMainWindow.show()
    sys.exit(app.exec_())
